# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'query.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 380)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.timeButton = QtWidgets.QPushButton(self.centralwidget)
        self.timeButton.setGeometry(QtCore.QRect(60, 210, 380, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.timeButton.setFont(font)
        self.timeButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.timeButton.setDefault(False)
        self.timeButton.setFlat(True)
        self.timeButton.setObjectName("timeButton")
        self.queryButton = QtWidgets.QPushButton(self.centralwidget)
        self.queryButton.setGeometry(QtCore.QRect(60, 310, 380, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.queryButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/Downloads/blue_query_96px_1075411_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.queryButton.setIcon(icon)
        self.queryButton.setAutoDefault(False)
        self.queryButton.setDefault(False)
        self.queryButton.setFlat(False)
        self.queryButton.setObjectName("queryButton")
        self.exchangeButton = QtWidgets.QPushButton(self.centralwidget)
        self.exchangeButton.setGeometry(QtCore.QRect(230, 160, 40, 40))
        self.exchangeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../.designer/backup/Pictures/exchange2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exchangeButton.setIcon(icon1)
        self.exchangeButton.setFlat(True)
        self.exchangeButton.setObjectName("exchangeButton")
        self.highSpeedCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.highSpeedCheckBox.setGeometry(QtCore.QRect(340, 265, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.highSpeedCheckBox.setFont(font)
        self.highSpeedCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.highSpeedCheckBox.setAutoFillBackground(False)
        self.highSpeedCheckBox.setObjectName("highSpeedCheckBox")
        self.studentCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.studentCheckBox.setGeometry(QtCore.QRect(60, 265, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.studentCheckBox.setFont(font)
        self.studentCheckBox.setObjectName("studentCheckBox")
        self.logoLabel = QtWidgets.QLabel(self.centralwidget)
        self.logoLabel.setGeometry(QtCore.QRect(185, 10, 130, 130))
        self.logoLabel.setText("")
        self.logoLabel.setObjectName("logoLabel")
        self.startLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.startLineEdit.setGeometry(QtCore.QRect(60, 160, 170, 40))
        self.startLineEdit.setObjectName("startLineEdit")
        self.destinationLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.destinationLineEdit.setGeometry(QtCore.QRect(270, 160, 170, 40))
        self.destinationLineEdit.setObjectName("destinationLineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiondenglu_12306 = QtWidgets.QAction(MainWindow)
        self.actiondenglu_12306.setObjectName("actiondenglu_12306")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "12306购票"))
        self.timeButton.setText(_translate("MainWindow", "出发日期"))
        self.queryButton.setText(_translate("MainWindow", "查询车票"))
        self.highSpeedCheckBox.setText(_translate("MainWindow", "高铁动车"))
        self.studentCheckBox.setText(_translate("MainWindow", "学生票"))
        self.actiondenglu_12306.setText(_translate("MainWindow", "denglu 12306"))

